### PR TITLE
Create snicosia.md

### PR DESCRIPTION
**Pull request by snicosia**
# Application to the Class of 2021🎓

This pull request template helps you complete an application to the **Class of 2021**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrM5IigBuRFaj33H).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by snicosia** [comment]
Still waiting for PR approval

**Comment by snicosia** [comment]
@elisemoe Hi Elise sorry for tagging. I had this pull request open for two days but was never approved. Not sure why the bot wasn't picking it up. I reopened a new one but I doubt it ti will be in the first 5000 merged PRs. This is the new PR https://github.com/education/GitHubGraduation-2021/pull/9490

Thanks,
Salvo

**Comment by elisemoe** [comment]
Hi @snicosia 👋 Please reopen this pull request and tag me again to keep your swag eligibility. I'll re-request the bot to review.

**Comment by snicosia** [comment]
@elisemoe Hi Elise thanks I have re-open it.

**Comment by elisemoe** [comment]
Hello! It does seems this was an error with our bot. We've merged the first 5,000 pull requests for swag but please [fill out this form](https://airtable.com/shrZuXu2OKrxO6PiD) and our team will approve you for swag on Monday.

**Comment by snicosia** [comment]
Thank you so much Elise!

**Comment by elisemoe** [comment]
Welcome to graduation! Due to the error with out bot, you are eligible for swag and will receive something in the mail ✨

**Comment by snicosia** [comment]
@elisemoe. Hi Elise. I was just wondering if the swag was already shipped out. I will be moving out out of my current place at the end of this month and just wanted to make sure I would receive them on time while I’m still here. Thanks.

**Comment by elisemoe** [comment]
Hi @snicosia 👋 I would recommend updating your address as the swag is still in production and has had a few delays. You can do so by submitting a new address in the text field of [this form](https://airtable.com/shrZuXu2OKrxO6PiD).

**Comment by elisemoe** [comment]
Hello 👋 Writing to let you know your address has been updated.

**Comment by snicosia** [comment]
Hi @elisemoe, I’m writing to let you know that I haven’t received the swag. Only thing that came in the mail was the card. Could you let me know if it was shipped? Also what am I expecting to receive as part of the swag? Thanks.

**Comment by elisemoe** [comment]
Hello 👋 as described in the readme, the custom trading card is the swag.

**Comment by snicosia** [comment]
Thanks @elisemoe. I received it then.

**Pull request merged**
