### PR TITLE
Github Graduation 2021 PR

### PR DESCRIPTION
**Pull request by navinbarnwal**
# Application to the Class of 2021🎓

This pull request template helps you complete an application to the **Class of 2021**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrM5IigBuRFaj33H).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Comment by navinbarnwal** [comment]
@GitHub-Education-bot test and approve this pls, it's been 2 hrs.

**Comment by VedantKhairnar** [comment]
@navinbarnwal Pls let me know when you get some update. I am waiting for the same. Will let you know too!

**Comment by navinbarnwal** [comment]
> @navinbarnwal Pls let me know when you get some update. I am waiting for the same. Will let you know too!

Sure bro!!

**Comment by navinbarnwal** [comment]
test Getting grades

**Comment by navinbarnwal** [comment]
> @navinbarnwal Pls let me know when you get some update. I am waiting for the same. Will let you know too!

@VedantKhairnar bro I think you should also contact @elisemoe to re run the test. Later they just approve within minutes.

**Comment by elisemoe** [comment]
Looks like your all good! Our team will be by in the next day to merge your pull requst.

**Comment by navinbarnwal** [comment]
> Looks like your all good! Our team will be by in the next day to merge your pull requst.

Sure, I'll eagerly be waiting🤗

**Comment by navinbarnwal** [comment]
> Looks like your all good! Our team will be by in the next day to merge your pull requst.

@elisemoe By mistake I forgot to provide my full address in the form. Is it possible to change the details now?

**Comment by elisemoe** [comment]
@navinbarnwal I've emailed you to update the address

**Comment by navinbarnwal** [comment]
> @navinbarnwal I've emailed you to update the address

@elisemoe  Thankx I emailed the updated one.

Thank you so much.

**Pull request merged**
