### PR TITLE
Create esikmalazman.md

### PR DESCRIPTION
**Pull request by esikmalazman**

### CODE REVIEW

**Comment by elisemoe** [comment]
Hi esikmalazman 👋 Thanks for submitting your PR to the graduation repo! It looks like you've added the Issue template text to the markdown file. Can you please remove the checklist and text before I approve your pull request?

**Comment by esikmalazman** [comment]
Hi, yes sure, I already remove it

**Review by esikmalazman — COMMENTED** [review]
Remove checklist

**Review by elisemoe — APPROVED** [review]
Congratulations on graduating 🎓🎉. Your submission has been approved and you're now part of the class of 2021! We will send you a 📦| ✉️ with swag to your home. Stay tuned for updates through our social media accounts.

**Pull request merged**
