### PR TITLE
Create rahuldey613.md

### PR DESCRIPTION
**Pull request by rahuldey613**
# Application to the Class of 2021🎓

This pull request template helps you complete an application to the **Class of 2021**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrM5IigBuRFaj33H).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Review by elisemoe — APPROVED** [review]
Congratulations on graduating 🎓🎉. Your submission has been approved and you're now part of the class of 2021! We will send you a 📦| ✉️ with swag to your home. Stay tuned for updates through our social media accounts.

**Comment by elisemoe** [comment]
Hi @rahuldey613! Responding to your message on swag. We are still many weeks away from the cards arriving as we need to have them produced. Production will start next week and we will update the repository readme when the cards have shipped!

**Comment by rahuldey613** [comment]
Respected Maam,
It's been a while having heard from you, the time given in the repository
is nearly up ,
By when can we expect our swags in India.If you could tell us.

Thanks & Regards
Rahul Dey

**Comment by rahuldey613** [comment]
Hi @elisemoe @GitHub-Education-bot ,
It's been a while having heard from you, the time given in the repository
is nearly up and the form for the lost package is also not published in the repo ,which was suppose to be their by 31st jan

**Pull request merged**
